### ISSUE TITLE
how to move an inserted shape or text ?

### ISSUE THREAD

**Issue by niconil** [amcharts/export#13]
maybe not an issue but more a misconfigured chart, i don't know

with the export module i can add shape and text
but there all coming to the center of the chart and i have not found how to move them (annoying)

i'm using 3.15.1 version of amcharts (with 1.2.1 version of export plugin)
and i try to update to lateste version of export plugin (1.2.8) but does not help

when i try to grab the object (shape or text) my pencil draws line ...

**Comment by maertz** [comment]
The plugin is always in drawing mode to be able to draw on top of other elements and prevent selecting them within their boundary box. Simply click on the element to select it once you see the "border with squares" you will be able to move,rotate,scale or remove it ( delete | backspace key ). Text elements are by default in writing mode when adding, click beside the element to deselect and select normally. Double click on text will reenter edit mode.

**Comment by niconil** [comment]
ok i understand

but on my config i have to click between 10 - 20 times to make appear the border with squares
i have a lack of responsiveness
but i don't know why ?
css ? page (html code)  containing the graph ? CPU too weak ?

thanks for your answer

**Comment by maertz** [comment]
There were no issues at all in our tests, please let us know which browser/operation system you are using to try to reproduce this.

**Comment by mg1075** [comment]
@niconil - how small is the font size of your text element? I noticed a similar problem until I purposely increased the size of the text.

**Comment by maertz** [comment]
When adding text elements the default font size is obtained from the chart instance (by default 11px) once changed it takes the values from the export menu times 3.
