### ISSUE TITLE
dateFormat settings?

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#14]
Is there a working example showing how to customize the output of dates in both CSV and XLSX?

```
export: {
    enabled: true,
    dateFormat: "MMM D, YYYY JJ:NN:SS"
}
```

**Comment by maertz** [comment]
XLSX does not obtain the given format by default, instead it converts the date fields to real "excel date fields" you need to format those within your spreadsheet program.

To bypass that default behaviour you need to export manually by calling [toXLSX](https://github.com/amcharts/export/blob/master/export.js#L1897) with your `dateFormat` or comment [this line](https://github.com/amcharts/export/blob/master/export.js#L1900)
