### ISSUE TITLE
add ability to append css classes to the root export div

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#15]
Just thinking it might be useful to provide a hook into the css of the **base export div** as a way to enable customizations and overrides of styling. The hook would **not** remove the base class names, but it would allow you to add an additional class name (or names) to the root div.

**Comment by maertz** [comment]
The amCharts core allows you to change the CSS-classname prefix by adding `classNamePrefix` to your chart setup. The export plugin do respect that property but do not forget to adapt your `export.css` as well.
```
    AmCharts.makeChart("chartdiv",{
        classNamePrefix: "test123"
    });
```
On the other hand you can simply overwrite our defaults if your CSS definition is below `export.css` e.g.:
```
		<link  type="text/css" href="./amcharts/plugins/export/export.css" rel="stylesheet">
		<style type="text/css">
			.amcharts-export-menu .export-main > a {
				background-color: #FF00FF;
			}
			/* IN CASE OF classNamePrefix */ 
			.<classNamePrefix>-export-menu .export-main > a {
				background-color: #FF00FF;
			}
		</style>
```

**Comment by mg1075** [comment]
Yep, but that seems to be a dramatically overkill way to go about customizing or overriding if all you want to do is customize a few properties.

For instance, if I just want to override the default export.css setting for a top-right-menu "top" property by having "top" be 20px instead of 0, there is no justification for creating a custom classNamePrefix that renders the existing structure of the export.css useless unless I add a bunch of new class names to the default class names in export.css.

**Comment by maertz** [comment]
Please adapt the `export.css` to you needs
            .amcharts-export-menu .export-main > a {
                background-color: #FF00FF;
            }
or overwrite the conditions as following to be independent of the upcoming updates which might include CSS changes:
        <link  type="text/css" href="./amcharts/plugins/export/export.css" rel="stylesheet">
        <style type="text/css">
            .amcharts-export-menu .export-main > a {
                background-color: #FF00FF;
            }
            /* IN CASE OF classNamePrefix */ 
            .<classNamePrefix>-export-menu .export-main > a {
                background-color: #FF00FF;
            }
        </style>
