### ISSUE TITLE
Images are not working 

### ISSUE THREAD

**Issue by chfakht** [amcharts/export#16]
Hi i'm using the field balloonText to display the image in the charts like this

balloonText: img src='images/fly.png' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>[[value]]</b></span>

the only images that works are the ones in images folder in amcharts , i have tried with many png images downloaded from the internet but none of them works
maybe i need some modifications on images to make them works !!!
please help
thanks

**Comment by martynasma** [comment]
Hi there,

I suppose those images are loaded from different domain than the web page itself. Images like these are considered "tainted" by browser. Our export script cannot access those images due to security restrictions. That's why they are removed before exporting.

To fix that, you will need to make sure the images are loaded exactly from the same web site as the web page displaying the chart.

**Comment by maertz** [comment]
Exactly, that is the general behaviour for embedded images within the SVG element.
Unfortunately the content of the balloons are outside the SVG element and are therefor not able to capture, currently the export plugin grabs only the textual content and place it on top of the captured chart. There is no possible work around to solve this issue at the moment.

**Comment by chfakht** [comment]
@martynasma  Hi again , i have downloaded the test images to the image folder like it in amcharts but it won't work
@maertz i have tested with an svg image and doesn't work , so you are seeing that i can't test any images for now 
thanks

**Comment by maertz** [comment]
Exactly, only the textual content gets exported and might have visual differences from the HTML/CSS definition because it overtakes only fontSize, fontColor and fontFamily at the moment. Sorry when i was unclear.

**Comment by chfakht** [comment]
@maertz , I didn't understund well because i'm not a native english speaker :yum:  , but i don't understunfd why the SVG image won't work , so how you have created those images (bicycle.png  car.png  motorcycle.png) and make them works ? :walking:

**Comment by maertz** [comment]
![visualised](https://cloud.githubusercontent.com/assets/921705/9407548/8d3e2a12-480a-11e5-8d92-39a186b5bbc9.jpg)

The balloon is not a part of the SVG element of amCharts, that's the reason it does not get exported. I hope the graphic helps you to understand the structure of amCharts and it's balloons :)

**Comment by chfakht** [comment]
:ok: thanks , so i can't have my own svg images and pass them to the plugin to make them works right , sorry for the repetition

**Comment by maertz** [comment]
Correct, not supported inside the balloons.
