### ISSUE TITLE
exporting data when date field is timestamp rather than date object

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#17]
For the XLSX and CSV download options, if using the categoryField has a date and the date is sent to the dataprovider as a timestamp rather than a date object, is there a way - out of the box - to make the download treat the date field as a date instead of an integer?

**Comment by maertz** [comment]
We've just released a new version `v1.3.1` which solves the issue. Date-Field-Timestamps get converted as dates. XLSX and JSON export by default `date objects` if no `dateFormat` has been defined.
Define `dateFormat: 'dateObject'` to export the RAW dates, if you prefer a dedicated date format for CSV but a real "date field" for XLSX you need to use the `menuReviver` to pass the dedicated [`dateFormat`](https://github.com/amcharts/export#format-specific-options-that-you-can-override-using-menu-item-reviver).

**Comment by mg1075** [comment]
Thanks!
