### ISSUE TITLE
Exporting without amcharts

### ISSUE THREAD

**Issue by piernik** [amcharts/export#18]
This plugin works great and I was wondering weather it can be used as a standalone script for exporting purposes.
Example I have my own table with data and want to export it to csv or excel or even PDF. Can I use this script somehow?

**Comment by maertz** [comment]
Sure, ensure to serve the 'AmCharts' namespace within the 'window' object before you include the export resources. Once you have all that you are ready to create your export instance and generate the files like following:

	<script type="text/javascript">
		// Server namespace with required variables
		window.AmCharts = {
			translations: {},
			addInitHandler: function() { /* NOOP */ }
		};
	</script>

	<script type="text/javascript" src="http://amcharts.com/lib/3/plugins/export/export.js"></script>

	
	<script type="text/javascript" src="http://amcharts.com/lib/3/plugins/export/libs/jszip/jszip.js"></script>
	<script type="text/javascript" src="http://amcharts.com/lib/3/plugins/export/libs/xlsx/xlsx.js"></script>

	
	<script type="text/javascript" src="http://amcharts.com/lib/3/plugins/export/libs/FileSaver.js/FileSaver.js"></script>

	
	<script type="text/javascript">

		// CREATE EXPORT INSTANCE
		var ame = new AmCharts.export({},{
			// Export settings
		});

		// DATA ARRAY
		var data = [ {"country": "USA","visits": 2025}, {"country": "China","visits": 1882}, {"country": "Japan","visits": 1809}, {"country": "Germany	","visits": 1322}, {"country": "UK","visits": 1122}, {"country": "France","visits": 1114}, {"country": "India","visits": 984}, {"country": "Spain","visits": 711}, {"country": "Netherlands","visits": 665}, {"country": "Russia","visits": 580}, {"country": "South Korea","visits": 443}, {"country": "Canada","visits": 441}, {"country": "Brazil","visits": 395} ];

		// CONVERT DATA TO CSV
		ame.toCSV({
			data: data

		// CONVERT CALLBACK
		},function(base64) {
			var info = this.defaults.formats.CSV;
			var filename = this.config.filename + "." + info.extension;
			var mimetype = info.mimeType;

			// OFFER OUTPUT AS DOWNLOAD
			this.download(base64,mimetype,filename);
		});
	</script>

**Comment by piernik** [comment]
Thank vary much - I'll try it tommorow. You should think of releasing You plugin as a standalone script - it's great

**Comment by mg1075** [comment]
That would be nice - I thought this was not possible, as per an earlier question.
https://github.com/amcharts/export/issues/10

**Comment by maertz** [comment]
@mg1075 it is still not possible to capture the whole HTML document. Although it's possible to process custom data as mentioned above, since we've exposed the API constructor few versions ago and enhanced the internal data management.

@piernik Thanks, let's see what shows up in the feature ;)

**Comment by mg1075** [comment]
@maertz - For clarification: is it only possible to expert **data** for a non-amcharts element, or is it also possible to use the plugin to export non-amcharts document elements? E.g., if a person wanted to export part of the page as PDF, PNG, JPG, or SVG, would the plugin make this now possible?

**Comment by maertz** [comment]
Only non-amcharts **data** can be exported through the approach mentioned above. **Visual data** is not possible (non-amcharts elements), therefore html2canvas might be an option for you.
