### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#19]
Curious if you have seen any issues with increased consumption of memory due to this plugin? It includes a number of 3rd party libraries for xlsx, pdf, etc. When I do not include the export plugin, the memory hit for an amCharts chart is not as bad.

**Comment by maertz** [comment]
Nothing special, just the dedicated payload of the 3rd party libs. The plugin loads them once the first chart with export enabled has been initiated. You can disable that feature by disabling ' autoLoad'  or adapting the resources array to load only those which you need.

	{
		"enabled": true,
		"libs": {
			"autoLoad": true,
			"resources": [ "fabric.js/fabric.js", "FileSaver.js/FileSaver.js" ],
			"path": "../../AmPlugins/export/libs/"
		}
	}

Do you've any further details about your assumption of the memory leak?
