### ISSUE TITLE
scrollbar color when zoomed: export image shows only one color

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#21]
This was produced on a stock chart with zoom features. 

Here's part of the chart original. Note the zoom handles, and how the background color of the scrollbar is different between the zoomed in vs. the zoomed out portions.
![image](https://cloud.githubusercontent.com/assets/2031435/10088584/701ebfcc-62e1-11e5-864d-1b548d80c2c3.png)

And here's a picture of the image export. Notice how the zoomed in and zoomed out portions now have the same background color.
![image](https://cloud.githubusercontent.com/assets/2031435/10088565/5a6c0338-62e1-11e5-825b-3565682515a7.png)

**Comment by maertz** [comment]
Fixed with the v1.3.5 update. Thanks for pointing this out.
