### ISSUE TITLE
Noob trying to figure out the export functions

### ISSUE THREAD

**Issue by trosenthaltaconic** [amcharts/export#26]
I'm trying to figure out how to add a watermark/logo on my exported files but I can't get the JSON file to validate. I know I'm missing something stupid like a coma but I don't know where. 

I've add the beforecapture to my export but again it just keeps saying there is something wrong. 

[export-beforecapture.txt](https://github.com/amcharts/export/files/133004/export-beforecapture.txt)

**Comment by maertz** [comment]
Looks fine to me, just ensure the image you are going to embed comes from the same origin (http://info.taconic.com/) as your chart otherwise it violates the cross resource origin security policy (CORS)

**Comment by trosenthaltaconic** [comment]
Well I tried using base64 string such as http://info.taconic.com/hubfs/images/logos/taconic-stacked-logo.png;base64,77+977+9ae+/ve+/ve+/vX7vv71acu+/ve+/vXHvv70m77+9G++/vX7vv73image77+977+9aO+/ve+/vT/vv73vv70o77+9Jyzvv73vv70kee+/vWjvv73vv71n but that doesn't work either

**Comment by maertz** [comment]
Unfortunately by simply changing the output type from server side won't work, you really need to embed the whole base64 string into javascript to bypass the CORS issue. Please take a look to following sample, which shows you how to do so:

http://codepen.io/team/amcharts/pen/df25fb675a38482c510c1ce353a91c9a?editors=0010

fyi: i used https://www.base64-image.de/ to convert images into base64 data strings.

**Comment by trosenthaltaconic** [comment]
I figured out part of the issue and the image is now rendering. Now I just need to understand the scaleX and scaleY numbering to figure out how to size the image properly.

**Comment by maertz** [comment]
I've updated the [sample](http://codepen.io/team/amcharts/pen/df25fb675a38482c510c1ce353a91c9a?editors=0010), it places your image into the center of the canvas (plotarea).

The scale (`scaleX, scaleY`) defined the image size in a percentage-ish value from 0-1.
The origin (`originX, originY`) sets the anchor point where the image will be dragged from.

You might want to take a look into the [official fabricJS docs page](http://fabricjs.com/docs/fabric.StaticCanvas.html#setOverlayImage) which explains the `setOverlayImage` method in a deeper detail.

**Comment by trosenthaltaconic** [comment]
Gotcha - I was just reviewing that. How come when I use  originX: 'right', and originY: 'bottom' the image never shows up but when I use left and top it works?

**Comment by maertz** [comment]
Because most likely you are outside the canvas, if you drag the image origin point from the center to the right bottom, you need to cancel the offset through the top, left property. In this case by 250px to drag it back to the center point.

Initial sample: top,left and origin at the center (no offset needed):
http://codepen.io/team/amcharts/pen/df25fb675a38482c510c1ce353a91c9a?editors=0010

Origin right bottom sample: top, left with an additional 250px (half image size) to cancel the offset:
http://codepen.io/team/amcharts/pen/3f228704a333c4a8361fa318fc0af46a?editors=0010

**Comment by satinder1208** [comment]
Hi trosenthaltaconic,

How you sroted the issue of base64 format. I am stuck in a problem with data:image/jpeg;base64,77+977+977+977+9AB...

Thanks in advance

**Comment by trosenthaltaconic** [comment]
Yes, I've using this without issues for about a month. https://www.base64-image.de/ has been a huge help.
