### ISSUE TITLE
Adding new shapes currently available in StockEvents

### ISSUE THREAD

**Issue by debsush** [amcharts/export#27]
Hi,

I would like the shapes feature to include the StockEvents types ("flag", "sign", "pin", "triangleUp", "triangleDown", "triangleLeft", "triangleRight", "text", "arrowUp", "arrowDown").  Is this possible to have these shapes added in colorful format

Regards,
SD

**Comment by martynasma** [comment]
You can use any SVG as a shape in annotation. Take a look at this section in the documentation:

https://github.com/amcharts/export#annotation-settings

It shows how you can define your own list of shapes.

However, the shapes will probably not be able to be shown in multiple colors.

**Comment by debsush** [comment]
Thank you for the prompt response.  I have gone through the documentation.  Based on what I understood, currently we can pick up the shapes from the shapes folder.

"shapes": [ "test.svg" ], // Choice of shapes offered in the menu (shapes are being loaded from the shapes folder)

I am not sure if the shapes folder "https://github.com/amcharts/export/tree/master/shapes" currently has the symbols that are part of the StockEvents.  Was wondering if you could add these additional symbols to the folder mentioned above.  As far as color is concerned, I only need the arrowDown and arrowUp symbols to be in available in RED and GREEN colors.  Is it doable?

Regards,
SD

**Comment by martynasma** [comment]
No, those shapes are not there now. You can add any SVG there. I suggest looking for SVG icons on https://www.iconfinder.com/

You can then put those SVGs into shapes folder, then use `shapes` array to define which ones to add.

**Comment by debsush** [comment]
Thank you.  What is the default size that we should use.  Do you use the 128*128 or some other configuration.

**Comment by martynasma** [comment]
Default built in size of the shapes are 32x32px.

However, that size does not matter a lot, since SVG is a vector-based format. So the images will scale without any loss to quality both ways.

**Comment by debsush** [comment]
Can I send you a list of icons downloaded from iconfinder.com and you can help me push those images into the Shapes folder as I do not seem to have the access level to push files into the Shapes folder.

Thank you
SD

**Comment by martynasma** [comment]
You will need to add those icons into your own folder. Or clone this repository and add those icons to your own. This way you will be able to keep main Export plugin files in sync, while at the same time maintain your own copy of the shapes folder.
