### ISSUE TITLE
Retain current drawings when adding new dataSets to the chart

### ISSUE THREAD

**Issue by debsush** [amcharts/export#28]
Hi,

I would like to retain my current drawings (drawn using the new annotation feature) when I am out of the drawing mode.  That way, even if I add new indicators to the chart, I should be able to view existing drawings.  Current feature probably does not allow that or am I missing something?

Regards,
SD

**Comment by maertz** [comment]
It's not possible to retain the drawings across data updates.

**Comment by debsush** [comment]
Thank you for the prompt reply.  Is this something that is in the pipes.  I am happy to close the issue but in my opinion, this can be a great enhancement especially for AmStockCharts

**Comment by martynasma** [comment]
We will consider it. Thanks!

**Comment by maertz** [comment]
Hi @debsush, we've added an annotation API which might be the thing you were looking for.

Please check our [readme#annotation-api](https://github.com/amcharts/export#annotation-api) to dive into the new feature.

Sincerely Ben

**Comment by debsush** [comment]
Thank you.  This is great.  Would have appreciated a demo if possible.

Regards,
SD

**Comment by maertz** [comment]
sure, no problem, please take a look to following demo and follow these steps:

* Enter annotation mode
* Draw some things on it
* Press the "Save Annotations" button
* Exit Annotations mode
* Modify the datasets
* Enter the Annotation mode
* Press the "Place saved Annotations" button

http://jsfiddle.net/jmhqjhmm/

Sincerely Ben

**Comment by debsush** [comment]
It is not bringing back the saved annotation in my system. Not sure why
