### ISSUE TITLE
Conflict of pdfmake.js and lodash

### ISSUE THREAD

**Issue by MaokaiLin** [amcharts/export#29]
First, thanks for making this tool set available. It's very handy!

I am experiencing some trouble integrating the pdfmake lib with my codebase. The main cause is the conflict between the use of `_` (underscore) in pdfmake.js and the use of `_` in lodash.

My specific problem is that it gives me an error that `zipWith` function does not exist when I call `_.zipWith` function in my own code. Removing `pdfmake.js` file resolves that conflict, but the pdf export functionality is no longer available.

I didn't look closely into the `pdfmake.js` file, but my guess is that some use of `_` in that file is leaked into the global namespace. It is a serious bug if this is the case.

Could you take a look at it? Thanks a lot for the help!

**Comment by MaokaiLin** [comment]
actually took another look. pdfmake is using lodash 3.1.0, and `zipWith` is introduced in lodash 3.8.0.

note that lodash v3.1.0 is significantly behind the current version (4.5.1). but either way, the lodash library used in pdfmake should be strictly confined within the package. could you get this fixed?

**Comment by maertz** [comment]
Thanks for pointing this out, we simply include the default built from [pdfMake](https://github.com/bpampuch/pdfmake). They have already few issues regarding the namespacing issue, [one seems to be one you are looking for which respects the loDash global var](https://github.com/bpampuch/pdfmake/pull/443). On the other hand it might be fixed if you [manually include the resources](https://github.com/amcharts/export#2-manual) into your document and add the "loDash" resource after `pdfMake.js` file, that might already fix your issue by resetting the overwritten loDash methods.

**Comment by MaokaiLin** [comment]
Got it. I'll try it out later today and let you know if it works. Thanks for getting back so quickly.

**Comment by maertz** [comment]
any news?

**Comment by mg1075** [comment]
@maertz - I was wondering about some odd lodash behaviors. Yes, amcharts/pdfmake in front of lodash dependency overrides my app's lodash version. Putting (my newer or at least _expected_ version) lodash _after_ amcharts/pdfmake did override the old lodash version inside pdfmake.

**Comment by yaviner** [comment]
Hi,

I encountered this issue recently as well! I ended up fixing it by removing pdfmake as a dependency (I wasn't using this feature), but it's worth noting that the latest versions of pdfmake have fixed this: https://github.com/bpampuch/pdfmake/pull/443
