### ISSUE TITLE
Downloading the JPG image to a certain path in the server

### ISSUE THREAD

**Issue by debsush** [amcharts/export#34]
Hi,

I would like to  save the Amcharts JPG image in a server path without using any PHP and would like to know if I can use the export plugin for the same.

In the example below, onclick function will download the chart in JPG format directly into the Downloads folder of the user's desktop.  Can I tweak it to save the chart in a particular server path (say ~Home/Script/102/Terminal) so that I can later use the file saved in the server path for further processing like uploading onto imgur.com etc. (the upload onto imgur.com etc will be done outside of Amcharts ofcourse)

"export": {
  menu: [ {
    label: "JPG",
    click: function() {
      this.capture({},function() {
        this.toJPG( {}, function( data ) {
          this.download( data, "image/jpg", "amCharts.jpg" );
        });
      });
    }
  } ]
}

**Comment by martynasma** [comment]
JavaScript can't save anything on server without some server-side "intermediary" such as PHP script that can receive the image data and save it to local file system.
