### ISSUE TITLE
Update Fabric.js to 1.6.2

### ISSUE THREAD

**Issue by NPC** [amcharts/export#36]
Hi guys,

Latest version of Fabric.js is v1.6.2 (https://github.com/kangax/fabric.js/tree/master/dist), and it fixes some issues for creating canvas from SVG (for me transform: rotate() was completely wrong), so it may be good to update it in AmCharts/export too.

I just use it for converting some non-AmChart graphs for export, and it is convenient since I already have AmCharts on the page, so don't need to load it additionally.

**Comment by maertz** [comment]
Hi Anton,
Thanks for pointing this out, we will verify this release and let you know when we've updated fabric.

**Comment by NPC** [comment]
I understand, you have to be careful with what they could break :) Thanks for looking into this!

**Comment by maertz** [comment]
Hi Anton, 

We have verified that fabric version and were not able to find any issues. Please find the new version within the most recent commit https://github.com/amcharts/export/commit/dd2ffe872d906effd77fd2c2a9708bc5f2dea9f7.

Sincerely
Benjamin

**Comment by NPC** [comment]
Thanks Benjamin!
