### ISSUE TITLE
Include background image in captured screenshot?

### ISSUE THREAD

**Issue by snegostup** [amcharts/export#4]
I'm using an image with ```position: absolute``` as a background of the chart, but it doesn't appear on the captured screenshot. Is there a way to include it to the screenshot? Thanks.

**Comment by maertz** [comment]
doable using `beforeCapture` to set a `backgroundImage`, please ensure the image loads from the same origin as you website otherwise you will hit the CORS  (cross origin resource security) of your browser and the canvas get marked as "tainted" which prevents us from getting the image data.

	"export": {
		"enabled": true,
		"beforeCapture": function() {
			var canvas = this.setup.fabric;
			canvas.setBackgroundImage( "< image url >", canvas.renderAll( canvas ) );
		}
	}
