### ISSUE TITLE
Color names not recognized properly

### ISSUE THREAD

**Issue by gerric** [amcharts/export#40]
Hi guys,

referring to [this](http://stackoverflow.com/questions/38612284/why-amcharts-export-changes-color-to-black-and-white) SO post.
It seems like color names aren't recognized for exporting (and annotation) the same way they are for normal SVG rendering.

e.g. "orange" must be all lower-case to work for export

**Comment by alijamal14** [comment]
Thank You  @gerric for identifying
Here is the video of reproduced error

`<iframe width="560" height="315" src="https://www.youtube.com/embed/oyQLlDgdvMc" frameborder="0" allowfullscreen></iframe>`

**Comment by maertz** [comment]
It's a limitation from [fabricJS](https://github.com/kangax/fabricjs.com/) which does not understand all color names and return "black" as a default. I suggest to use HEXadecimal or RGBA codes.
