### ISSUE TITLE
Retain annotations on page after downloading the file

### ISSUE THREAD

**Issue by anrchen** [amcharts/export#42]
After adding an annotation, if the user downloads the file(no matter the type of file), the annotation made will disappear from the page. Same as printing the amCharts.

**Comment by maertz** [comment]
You are probably looking for the "drawing.autoClose" settings.
```
  "export": {
    "enabled": true,
    "drawing": {
      "autoClose": false
    }
  }
```
http://codepen.io/team/amcharts/pen/0e4a24da7b32f20015a624696f2baee2?editors=0010
