### ISSUE TITLE
Only 1 dataset is shown when downloading a chart. Save as works as expected

### ISSUE THREAD

**Issue by KoenVanduffel** [amcharts/export#43]
I have a serialchart with 5 datasets. All 5 are shown on the graph and all 5 are present when saving as XLSX. When I download a JPG, PDF, SVG or PNG I only get the 4th dataset to show on the image. There is no special setup in the export section:
	"export": {
    	"enabled": true,
        "position": "bottom-right"
     }
All 5 graphs have the same time axis, have complete datasets and are only different in colors and Y-axis they are referred to.

Is this a bug in the library or am I overseeing something?

**Comment by maertz** [comment]
Everything seems fine on my side, if it works on your side as well, ensure you've the most recent version of the plugin in your project.

Stock: http://codepen.io/team/amcharts/pen/80c453a0d9c1bb725b1a5eeea762fe44
Serial: http://codepen.io/team/amcharts/pen/df6a5827fa8d7cf6c47e6ed33e3d08bb

**Comment by KoenVanduffel** [comment]
Thanks for the quick answer. My library was downloaded just a few weeks ago and I did not check for an update.... sorry about that. The latest version works as perfectly!!

**Comment by maertz** [comment]
Alright, glad to hear it works now - you are welcome :)
