### ISSUE TITLE
Not showing icon

### ISSUE THREAD

**Issue by samiraguiar** [amcharts/export#45]
For some reason the plugin is failing to show the main icon. It shows only the button:
![image](https://cloud.githubusercontent.com/assets/13439135/17621946/8aa3515c-606d-11e6-86f8-11efecb066d3.png)

It tries to load the url `http://localhost:80/assets/global/plugins/amcharts3/amcharts/plugins/export/data:image/svg+xml;charset=utf8,<svg xmlns="http:/www.w3.org/2000/svg" xmlns:xlink="http:/www.w3.org/1999/xlink" width="11px" height="14px"><path d="M3,0 L8,0 L8,5 L11,5 L5.5,10 L0,5 L3,5 L03,0" fill="#888"/><rect x="0" y="12" fill="#888" width="11" height="2"/></svg>`.

I've set the AmCharts path, the shapes are loaded correctly and I can add them to the graphs. Is there any configuration I'm missing?

**Comment by martynasma** [comment]
Do you mean you are setting `path` parameter of the chart? If that is so, could you please try commenting it out.

If that doesn't help, please do share your whole chart config so that we can test.

Thank you.

**Comment by samiraguiar** [comment]
Sorry @martynasma, I'm closing this since I'm out of time to dig it further. But as soon as I get back to this I'll reopen the PR. Thanks for the reply.
