### ISSUE TITLE
gradientRatio causes graph to disappear when downloading as a picture

### ISSUE THREAD

**Issue by maksuturvaict** [amcharts/export#46]
You can verify this bug with your donut chart demo: https://www.amcharts.com/demos/donut-with-radial-gradient/

It seems that if a chart has any values in gradientRatio-array, trying to save chart as an image will cause all slices to go transparent (excluding the borders) both on the page as well as in the saved image or pdf.

Everything goes fine if there are no gradientRatio parameter or if is an empty array.

**Comment by maksuturvaict** [comment]
This happens to with e.g. serial charts if you have more than one value in the fillColors-array (as a gradient).

**Comment by maertz** [comment]
We've released an [update](https://github.com/amcharts/export/commit/b44fa0e65bbd93af98356e7cf280779568ef658c) which solves this issue. Thank you for your patience.
