### ISSUE TITLE
error when exporting lineChart to PNG,JPG,PDF

### ISSUE THREAD

**Issue by erwinjnefer** [amcharts/export#47]
hello sir !,,, can u help me ?? :)
when i use line chart, i got errors :
TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)
fabric.min.js:1 TypeError: Cannot read property 'trim' of undefined(…)

i try to run the examples for line chart  on amchart web and i got the same error..
thank's

**Comment by martynasma** [comment]
Sorry for the inconvenience.

This was due to error in the CDN version of amcharts.js library.

It has been fixed and should not throw export errors anymore.

Just make sure you clear your browser cache.

**Comment by erwinjnefer** [comment]
Ok thank's heee.. i'll try it right now

**Comment by erwinjnefer** [comment]
Yesss... you're right sir..,, thanks so much...

**Comment by martynasma** [comment]
You're welcome.
