### ISSUE TITLE
annotation: text and geometric shapes

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#5]
Hello, 

Is this plugin going to have an update where geometric shapes and text annotations can be added?

Thanks.

**Comment by martynasma** [comment]
Yes. We're literally a day or two away from releasing an exciting new update. The annotations will support adding text, shapes, lines, arrows. Setting opacity, colors, weight for all of those.

Stay tuned!

**Comment by mg1075** [comment]
1.2.1 has been published, offering more advanced annotation features.
