### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by daniele-zurico** [amcharts/export#50]
Hello I'm trying to include:

```
require('script!../../../vendor/amcharts3/amcharts/plugins/export/export.min.js');
```

inside my project but when I try to enable the export property (the default one) I get:

```
Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```

**Comment by maertz** [comment]
Thanks for pointing this out, can you give me few more details to be able to reproduce this issue?

**Comment by daniele-zurico** [comment]
Hi @maertz the problem was related with the previous release. I bought amcharts and exports was  included but when you try to use it it fail for the above reason. Using the new version fix the problem
