### ISSUE TITLE
landscape for pdf or png

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#51]
Is there an example config setting for exporting pdf or png as landscape rather than the default of portrait?

**Comment by maertz** [comment]
It is only possible to set the page orientation for PDF exports, the others get exported as they are.
If you wish to change the chart itself you need to change the chart container first, let amCharts rerender to the new dimensions of it's container and trigger the export manually.

Following config generates the PDF in landscape mode:

  "export": {
    "enabled": true,
    "pageOrientation": "landscape"
  }

Check the Github page of pdfMake to explore all settings for the PDF export.
https://github.com/bpampuch/pdfmake

**Comment by mg1075** [comment]
cool; thanks!

**Comment by mg1075** [comment]
FWIW, one could make the case that having the default pageOrientation be landscape makes more sense than a default orientation of portrait. Just perusing through the various demo charts on the amCharts website, most of those charts will look better on a pdf with a wide view rather than a narrow one.
