### ISSUE TITLE
Possible to transpose csv export (download csv)?

### ISSUE THREAD

**Issue by jordanharding** [amcharts/export#52]
When exporting a stacked chart, it looks like this

![image](https://cloud.githubusercontent.com/assets/13383273/20898957/62bcb0d2-baf6-11e6-924c-5f72fa7fa0be.png)

I'd like it to look like this

![image](https://cloud.githubusercontent.com/assets/13383273/20899002/8dfdb8e0-baf6-11e6-8492-924eb900fa10.png)

is there a command that enables this? If not, what's the best way to do it?

**Comment by maertz** [comment]
There is no flag/command to simply "rotate" the data sheet but you might want to have a look into following sample, which uses the `processData` function to get that:

https://codepen.io/team/amcharts/pen/4b6702ccd62b51473273ba2411c1b08d

**Comment by jordanharding** [comment]
wonderful, thank you!
