### ISSUE TITLE
Italian language available

### ISSUE THREAD

**Issue by matteopelucco** [amcharts/export#53]
I've prepared an italian translation. Added here, I can not prepare now a pull request.
[it.txt](https://github.com/amcharts/export/files/657319/it.txt) (just rename to it.js)

If you want, you can inclued it, feel free.

**Comment by martynasma** [comment]
Thanks!

I think you missed the "Click to cancel". How would you translate that?

**Comment by matteopelucco** [comment]
Oh, Sorry!
It should be: "Clicca per annullare"

Thanks!

Il 17 dic 2016 6:26 AM, "Martynas Majeris" <notifications@github.com> ha
scritto:

**Comment by martynasma** [comment]
No worries.

There you go:
https://github.com/amcharts/export/commit/eb743d440381cd4dac7fd2a6a04b35e484baa577
