### ISSUE TITLE
With bower last version is 1.4.39

### ISSUE THREAD

**Issue by sfrinx** [amcharts/export#57]
Could you update the plugin in a newer version? 
Actually i need italian translation.
Thank you.

**Comment by sfrinx** [comment]
ok perfect. Thank you a lot!

**Comment by martynasma** [comment]
Hey the release got postponed to tomorrow. (Wednesday)

Sorry for the inconvenience.

**Comment by martynasma** [comment]
Just released 3.21.1 moments ago.

https://github.com/amcharts/amcharts3

**Comment by sfrinx** [comment]
Hi, today a retry to install amcharts/export with bower and it downloads 1.4.39 version. If i set another greater version i get this error: " ENORESTARGET No tag found that was able to satisfy".
could you help me please?

**Comment by martynasma** [comment]
That's weird. Current version contains 1.4.61:

https://github.com/amcharts/amcharts3/tree/3.21.1/amcharts/plugins/export

**Comment by sfrinx** [comment]
Ah ok I did't see that there is the export plugin directly inside amcharts3. Actually i import amcharts3-export with bower. Thank you!

**Comment by martynasma** [comment]
There's no separate Bower package for Export plugin. So yeah, the best way is to use the one bundled with amCharts itself.
