### ISSUE TITLE
Error: canvas area exceeds the maximum limit initial Retina Scaling

### ISSUE THREAD

**Issue by kby799** [amcharts/export#61]
I keep getting white screen when try to download PNG with iPhone7 and mobile simulators, chrome devtool has pointed `_initRetinaDisplay()`. Would you be able to have a look at it please?

Version that I am using is `1.6.2`

**Comment by kby799** [comment]
I have similar problem to [#3152](https://github.com/kangax/fabric.js/issues/3152) from `kangax/fabric.js`. 

My work around is to comment out these lines;

```
this.lowerCanvasEl.setAttribute('width', this.width * fabric.devicePixelRatio);
this.lowerCanvasEl.setAttribute('height', this.height * fabric.devicePixelRatio);
```

The function `_initRetinaScaling` called twice and on the second time the function being called, the width and height had scaled up from first time by `fabric.devicePixelRatio`.

**Comment by maertz** [comment]
I've updated the plugin, please use the most recent version of the plugin and it's dependencies.

**Comment by kby799** [comment]
@maertz 
Thanks Bny, it worked great on the simulators and iPhone 6. Now just waiting for our tester's comment.

**Comment by maertz** [comment]
Any news?

**Comment by kby799** [comment]
Sorry, things are keeping pile up. Anyway our tester got back and it was working. Thank you.
