### ISSUE TITLE
This method has been removed in JSZip 3.0, please check the upgrade guide.

### ISSUE THREAD

**Issue by devisbal** [amcharts/export#62]
Using XLSX export.
Call to function generate() is causing this problem.
This function now have the message on the subject.
Deprecated objects/methods has been removed:
The generate() method has been replaced by generateAsync() and generateNodeStream().
https://stuk.github.io/jszip/documentation/upgrade_guide.html

**Comment by maertz** [comment]
Thanks for pointing this out, looks like sheet-js does not support the new version. I've upgraded  jszip independently instead of taking it out of the sheet-js folder. I'll release an update to roll back.

**Comment by zcon-sanket** [comment]
Hey hi, maertz, We are facing same issue with JSZip 3.0, as you got the right way to handle this scenario could you please update the solution? It will make our life easy.
Thank you.
