### ISSUE TITLE
XLSX Export not working

### ISSUE THREAD

**Issue by cristinaITdeveloper** [amcharts/export#63]
I was trying to use the demo on the website and the XLSX export is not working
This is the error message printed in the browser console

<img width="1125" alt="schermata 2017-06-09 alle 13 08 28" src="https://user-images.githubusercontent.com/11472348/26973088-f40080b8-4d14-11e7-8ea9-24ef5f6b92b0.png">

**Comment by maertz** [comment]
Thanks for pointing this out, it has been fixed with the new release of this plugin v1.4.68

**Comment by cristinaITdeveloper** [comment]
Nice, Thank you!
Now I can use this library in my project :-D
