### ISSUE TITLE
Image does not export on Safari

### ISSUE THREAD

**Issue by jamiechong** [amcharts/export#65]
I'm using: 
Mac Sierra 10.12.5
Safari 10.1.1 

When trying to export an image from here: https://codepen.io/amcharts/pen/55d41c60b96b44e1a69c94feb8f8b63b

I get this console error.
`InvalidStateError (DOM Exception 11): The object is in an invalid state.`

The effect is that I cannot export images. 

Works fine on Chrome (only other browser I tested).

**Comment by maertz** [comment]
I've released an update, please update yours and you should be good to go.
