### ISSUE TITLE
amcharts-export-canvas class unexpected token

### ISSUE THREAD

**Issue by bennyAG** [amcharts/export#66]
Very strange.
Getting unexpected token from export.css.

.amcharts-export-canvas {
	position: absolute;
	display: none;
	z-index: 1;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	background-color: #fff;
}
Cant figure out.

**Comment by maertz** [comment]
Indeed very strange, are you sure it's caused by this part of css? Can you send me a working sample which produces this issue? In addition it would be nice to know which OS and browser are you using.

**Comment by bennyAG** [comment]
OS: ubuntu 14
Browser/Env : electron

**Comment by maertz** [comment]
Unfortunately I can't reproduce it on the fly but following issue might be related with this https://github.com/amcharts/export/issues/67#issuecomment-319638613. If that's not the case, please send me a working example to reproduce this behaviour.

**Comment by barocsi** [comment]
Just include it in any angular-cli project and you will see the error
   "scripts": [
        "../node_modules/ammap3/ammap/plugins/export/export.css.min"
]
