### ISSUE TITLE
Legend items overlap

### ISSUE THREAD

**Issue by thatsmeta** [amcharts/export#69]
Hi!
Legend items overlap in exports when the font family is changed via CSS.
See https://jsfiddle.net/kLr5qtmr/ and try exporting the chart.
What can I do to prevent this? Any help is appreciated.

**Comment by maertz** [comment]
Please apply the font family as well on the chart instance.
https://jsfiddle.net/kLr5qtmr/1/
I hope that helps.

**Comment by thatsmeta** [comment]
What do I do if my legend needs a different font family than the rest of the chart?

**Comment by maertz** [comment]
The legend has [no dedicated option](https://docs.amcharts.com/3/javascriptcharts/AmLegend) to change its font family, therefore the generated SVG does not contain such information from where the export plugin can grab from. I'm afraid it's the only option.

**Comment by thatsmeta** [comment]
Ok, thanks.
