### ISSUE TITLE
1.2.1 examples: increase default text size of text annotation, or change hover handle?

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#7]
Looking at the 1.2.1 examples that allow for text annotation, I notice that when I add a text annotation, it is slightly awkward at first to see how small the text is. I think you may have just increased it with 1.2.2, which I just grabbed and added to the example, but it still seems, perhaps, just a bit too small? Maybe increase another number?

![image](https://cloud.githubusercontent.com/assets/2031435/8780122/85cc945a-2ecc-11e5-8289-aa4a5aed6bd7.png)

Maybe part of the awkwardness comes from trying to hover over the item to select it. What seems to happen is if I have multiple annotations on a chart, and none of the annotations are currently selected, then when I hover over the annotation, the "crosshair" cursor displays. But my thinking is that if I hover over an annotation at any time, shouldn't the cursor be the "move" cursor so that you can be confident the item is selectable?

**Comment by maertz** [comment]
By default it uses the font size from the chart instance but you can overwrite that with following:
```
    "export": {
        "enabled": true,
        "drawing": {
            "fontSize": 20
        }
    }
```
The cursor changes only if an element has been selected, otherwise it would be not possible to start drawing on top of other elements.

**Comment by mg1075** [comment]
ok; thanks.
