### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by bravility** [amcharts/export#72]
I set this config,but it not working
`            export: {
                enabled: true,
                language: 'de'
            },
`

**Comment by maertz** [comment]
You need to set the language at chart level.
https://docs.amcharts.com/3/javascriptcharts/AmChart#language

**Comment by bravility** [comment]
@maertz 
it does not work too.
```
        var chartDiv = AmCharts.makeChart("chartDiv", {
            //....other config
            export: {
                enabled: true,
                // language: 'lt'
            },
            language: 'lt'
        });
```
