### ISSUE TITLE
amcharts annotation - Custom Path for shapes

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/export#75]
Hi there,

Good day, How can we set the custom file path for all annotation shapes.

Best Regards,
Mark

**Comment by martynasma** [comment]
Hi Mark,

While there's currently no dedicated setting to set path for those icons, you can still work around using `menuReviver`:

```
  "export": {
    "enabled": true,
    "menuReviver": function( cfg, li ) {
      if ( cfg.action == "add" ) {
        var url = 'http://mynewurl.com/shapes/' + cfg.label;
        cfg.icon = url;
        cfg.url = url;
        li.getElementsByTagName("img")[0].src = url;
      }
      return li;
    }
  }
```

I hope this helps.

**Comment by kevzlou7979** [comment]
Thanks for the feedback
