### ISSUE TITLE
amcharts : dynamic loading of themes

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/export#76]
Hi there,

Currently the only way to define themes requires the chart to be reloaded. Is there an api to just call ``` chart.setTheme("black"). ``` so that it will automatically set the theme without reloading the whole chart or graph.

Thanks,
Kevin

**Comment by martynasma** [comment]
No, I'm afraid there's no way to set the theme on a chart dynamically. It needs to be recreated.

Sorry.

**Comment by kevzlou7979** [comment]
Ok yeah I understand because the JS Themes needs to be reinjected all the time. But no worries will do the same example as you have

**Comment by rohit-sourcefuse** [comment]
This is still not possible? or now there is any way to just change the theme?
