### ISSUE TITLE
amcharts : ability to export annotation as JSON objects

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/export#78]
Hi there,

This is a feature request with Annotation API ``` getAnnotations() ``` return as JSON Object instead of plain Javascript Object. I think it will benefit a lot when saving this also for server purposes.

Best Regards,
Kevin

**Comment by maertz** [comment]
Thanks for the input I will consider that in the next release.

**Comment by kevzlou7979** [comment]
Cool
