### ISSUE TITLE
A new default for displaying the menu  and options?

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#8]
I wonder if you have considered another option for the default display of annotation tool menu options? It seems cumbersome to have to hover over multiple menus to be able to see all the options available. If triggering the annotation tool triggered the display of a static menu with most options visible by default, it might make the tool easier to use. Right now, it can get annoying to have to do so much hovering to select an option.

**Comment by maertz** [comment]
It is possible to overwrite the defaults to create you own menu. You can redefine the main menu:
```
"export": {
	"menu": [
		{
			"label": "Annotate Profile 1",
			"action": "draw" // uses default from drawing.menu
		},

		{
			"label": "Annotate Profile 2",
			"action": "draw",
			"menu": ["PNG","JPG","CANCEL"]
		}
	]
```
Or keep our main menu and adapt only the annotation menu instead:
```
"export": {
	"drawing": {
		"menu": [
			{
				"label": "Change color ...",
				"action": "draw.colors",
				"widths": [ "#FF000", "#000000", "#0000FF" ] // replaces the default choice
			},
			"PNG",
			"JPG",
			"CANCEL"
		]
	}
}
```
https://github.com/amcharts/export#annotation-settings
https://github.com/amcharts/export#-or-set-your-own-custom-options
