### ISSUE TITLE
Column opacity is lost when exporting as PNG

### ISSUE THREAD

**Issue by hesamat** [amcharts/export#83]
This is how my chart looks like before exporting:
![image](https://user-images.githubusercontent.com/7344976/44549200-999d3480-a6dd-11e8-81b0-c0d2b6876483.png)

In the exported image, all the bars have the same level of opacity:
![image](https://user-images.githubusercontent.com/7344976/44549255-c5201f00-a6dd-11e8-9863-7e9bc6b0c0b2.png)

P.S: I use RGBA to set the opacity of the bars.

**Comment by darlesson** [comment]
It would be recommended to use hexadecimal colours instead and [alphaField](https://docs.amcharts.com/3/javascriptcharts/AmGraph#alphaField) to refer to the alpha value in your data.

Please check a very simplified example of the setup below and [the working example](https://codepen.io/team/amcharts/pen/73d3d5694eba4e77ab398fbdc2f7bd9a?editors=0010):

```
var chart = AmCharts.makeChart( "chartdiv", {
  "type": "serial",
  "dataProvider": [ {
    "country": "USA",
    "visits": 2025,
    "alpha": 0.5
  }, {
    "country": "China",
    "visits": 1882
  }],
  "graphs": [ {
    "alphaField": "alpha",
  } ]
});
```

**Comment by hesamat** [comment]
@darlesson Cool. Thanks for your quick response. I ended up manipulating the hex color.
