### ISSUE TITLE
default hover color for shapes options

### ISSUE THREAD

**Issue by mg1075** [amcharts/export#9]
Using the default export.css file, the hover action for annotation shapes is black on black, and therefore makes the shape illegible.

![image](https://cloud.githubusercontent.com/assets/2031435/8782157/2e30ae90-2ed9-11e5-8e51-87fac4d3e23a.png)

It would be nice if the out-of-the-box export.css file had an alternate background hover color for the shapes. I realize anyone can customize the css file, but out of the box, the css file should not have to be altered for something of this nature. 

```
.amcharts-export-menu .export-drawing-shape a:hover {
	background-color: #f5f5f5;
}
```

![image](https://cloud.githubusercontent.com/assets/2031435/8782201/81c56e4c-2ed9-11e5-84bc-7a24604034a1.png)

**Comment by martynasma** [comment]
Thanks for bringing it to our attention.

Grab the latest export.css from the repo. It will invert those images on hover.

```
.amcharts-export-menu .export-drawing-shape a:hover img {
	-webkit-filter: invert(100%);
	filter: invert(100%);
}
```
